### PR TITLE
command: Support custom Prelude

### LINKED ISSUE #725: `ob run` does not work with own Prelude
#### To Reproduce

1. ob init
2. Create `common/src/Prelude.hs` add it to `common.cabal`
3. run `ob run`.

#### Error

```
Loading ghci -ignore-dot-ghci -no-user-package-db -package-env - -F -pgmF /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/.ob-wrapped -optF __preprocessor-apply-packages -optF backend/backend.cabal -optF common/common.cabal -optF frontend/frontend.cabal -ibackend/src:common/src:frontend/src -ghci-script /tmp/ob-ghci-f5ba8bc8df8585b5/.ghci ...
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help

<interactive>:1:1: error:
    attempting to use module ‘main:Prelude’ (common/src/Prelude.hs) which is not loaded
Command "ghci -ignore-dot-ghci -no-user-package-db -package-env - -F -pgmF /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/.ob-wrapped -optF __preprocessor-apply-packages -optF backend/backend.cabal -optF common/common.cabal -optF frontend/frontend.cabal -ibackend/src:common/src:frontend/src -ghci-script /tmp/ob-ghci-f5ba8bc8df8585b5/.ghci" exited unexpectedly with error message:     attempting to use module ‘main:Prelude’ (common/src/Prelude.hs) which is not loaded
```

This has something to do with a special handling of the name `Prelude` and is a regression. I didn‘t have the problem before bumping to master today.

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #725 

I have:

  - [x] Based work on latest `develop` branch
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by srid** [comment]
If I understand correctly, this PR would allow me to use a custom prelude like `relude` without necessarily having to use `No Implicit Prelude` in the app project?

**Comment by 3noch** [comment]
@srid See #725 for how @maralorn uses this.

**Comment by maralorn** [comment]
@srid Yeah, you can use NoImplicitPrelude to include your own Prelude (or Relude). Have a look at the relude README, they explain the various ways to do that.

**Comment by srid** [comment]
Yup I already use relude. That and ormolu have been the two new additions to my obelisk apps of late.

**Pull request merged**
