### PR TITLE
Fix mobile asset injection in default builds

### LINKED ISSUE #382: Loading of static files seems to be broken on Android
Reproduce:

- Build the default Obelisk project (Result of `ob init`)
- Run `nix-build -A android.frontend -o result-android`
- Deploy to your phone: `./result-android/bin/deploy`
- Start application on phone 
- Notice that the obelisk image is missing

Tested with current master: b2be6372bd263037cf89e1a68e0fd35dfd370f4e
Same issue on develop: abc320a6778a53a079ac7d411d2c5f31c38e0db3

image

### PR DESCRIPTION
**Pull request by kmicklas**
Fixes #382.

### CODE REVIEW

**Comment by ali-abrar** [comment]
@kmicklas let me know if this works when the static assets are a derivation instead of a folder.

**Comment by ali-abrar** [comment]
@kmicklas Merging this since it is an improvement over what's on develop now; we'll have to revisit the static-assets-as-derivation issue.

**Comment by adinapoli** [comment]
@kmicklas @ali-abrar Hey folks!

First of all, thank you so much for your work on Obelisk -- it made deploying Haskell apps on Android a breeze (and it really showcases the power of Nix :wink: ).

Unfortunately, exactly as the original user who posted the issue, even after this patch, my Android app doesn't render the static files correctly. 

I am pretty new to Obelisk and Nix, so I might be doing something wrong, hehe. In order, this is what I did:

1. Upgrade Obelisk to the latest version of `develop` by typing:

```
 nix-env -f https://github.com/obsidiansystems/obelisk/archive/develop.tar.gz -iA command
```

2. Bump the source code of my frontend app so that the derivation would be rebuilt. I have a bunch of static assets in my `static` folder (which is essentially the vanilla `ob init` app with small tweaks):

```
~/programming/haskell/buckets » tree static                                                                                                              alfredo@recursive
static
├── css
│   ├── bulma.min.css
│   └── index.css
├── js
│   ├── index.js
│   └── slideout.min.js
└── obelisk.jpg

2 directories, 5 files
```

(Obviously the Css and JS renders just fine locally when using `ob run`).

3. Invoke `nix-build -A android.frontend -o result-android`

Interestingly enough, I do see the following in the output:

```
building '/nix/store/48aaqr1hgknws96n11vq3h2lqcvvbs7m-android-app.drv'...
skipping non-regular file "obelisk.jpg"
skipping non-regular file "css/bulma.min.css"
skipping non-regular file "css/index.css"
skipping non-regular file "js/index.js"
skipping non-regular file "js/slideout.min.js"
building '/nix/store/h1km8bfh0fv6qzgwblzx9dw1r7b3hc12-systems.homset.buckets.drv'...
unpacking sources
unpacking source archive /nix/store/jdnkq1s9w7zwmsivcjs4kdd41hkw6pqx-android-app
source root is android-app
patching sources
configuring
no configure script, doing nothing
building

Welcome to Gradle 4.10!
[...]
```

5. Deploy on mobile with `./result-android/bin/deploy`

6. Observe that the static files are not rendered :broken_heart: (not even the stock `obelisk.jpg`)


What am I doing wrong?

**Comment by ali-abrar** [comment]
Thanks for the report. It doesn't look like you're doing anything wrong.
We'll investigate and let you know what we find.

**Comment by kmicklas** [comment]
> Bump the source code of my frontend app so that the derivation would be rebuilt.

@adinapoli This means you updated `.obelisk/impl` in your application source to point to the latest `develop`? I just wanted to make sure since updating the global Obelisk (with `nix-env`) isn't actually necessary or sufficient to get updates like this PR.

**Comment by adinapoli** [comment]
Ah! No, I had no clue I had to act on that directory, sorry! Can I simply
nuke it and call "ob init" again or is there a smoother upgrade path?

**Comment by kmicklas** [comment]
@adinapoli `ob thunk update .obelisk/impl --branch develop` will update to the latest `develop`.

**Comment by adinapoli** [comment]
Yay, it worked!

Thanks a lot for the assistance :)

A.

**Pull request merged**
