### PR TITLE
Changed command lines in "contributing" to include build tools

### PR DESCRIPTION
**Pull request by eskimor**
in spawned nix-shell.

This way the developer does not need to have cabal-install and ghcid in correct versions installed.

### CODE REVIEW

**Comment by ryantrinkle** [comment]
I think we should make these simpler before recommending them

**Comment by eskimor** [comment]
Will work something out!

**Comment by eskimor** [comment]
Done - commands are as simple as before.

**Comment by luigy** [comment]
Thanks!

**Pull request merged**
