### PR TITLE
Use system temp dir for temporary thunk clone

### PR DESCRIPTION
**Pull request by alexfmpe**
Obelisk seems not to handle the ssh prompt correctly so when that kicks in I have to cancel `ob thunk unpack` to get the ssh-agent going, and end up with cruft in my local directory, hence this PR.

I have:

  - [x] Based work on latest `develop` branch
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [x] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by lpsmith** [comment]
Actually this does have a problem:  I for one tend to put `/tmp` on `tmpfs`, (though I might also set up a user-specific `~/tmp` tmpfs and set `TMPDIR` accordingly)

As it turns out, this will cause `renameDirectory` to fail, as the temporary directory will be on a different block device/filesystem than the unpack location.

There's a similar-ish problem with #785.   We could say,  shell out to `mv`,  (or maybe emulate `mv` ourselves?  meh)

**Comment by 3noch** [comment]
Hm, shouldn't unpacking be bracketed so that if you kill it it deletes it's temporary dir?

**Comment by lpsmith** [comment]
> Hm, shouldn't unpacking be bracketed so that if you kill it it deletes it's temporary dir?

You can't entirely rely on `bracket` to clean up temporary files:  `kill -9` will prevent the clean up code from running;  not sure about GHC's default `SIGTERM` signal handler.

But yes, we could at least make obelisk clean up after itself after a `SIGTERM`.

**Comment by 3noch** [comment]
Yeah I'm not worried about SIGKILL. If you have to do that something is very broken and you should not be surprised when cruft is left behind. But that should happen basically never.

**Comment by alexfmpe** [comment]
Isn't it bracketed already? `withSystemTempDirectory` delegates to [withTempDirectory](https://hackage.haskell.org/package/temporary-1.3/docs/src/System.IO.Temp.html#withTempDirectory) which is a `bracket`

**Comment by alexfmpe** [comment]
Oh, but that's what was there before and it was still leaving cruft around on ctrl-c. 
Maybe something we're doing interferes with the cleanup

**Comment by 3noch** [comment]
Yeah that's my concern. Why isn't bracket handling this for us??

**Comment by alexfmpe** [comment]
I wonder if the git process doing the cloning ends up locking the directory while it's hanging on the ssh prompt. 
I'll try to test that when I have some time

**Comment by mankyKitty** [comment]
@ali-abrar move to `nix-thunk` ?

**Comment by ryantrinkle** [comment]
This should be handled with bracketing.  Also we can make the temp directory hidden if we aren't already.  It **should** be in the same directory as where it will end up so that it is on the same filesystem.

**Comment by alexfmpe** [comment]
> This should be handled with bracketing. 


> Isn't it bracketed already? withSystemTempDirectory delegates to [withTempDirectory](https://hackage.haskell.org/package/temporary-1.3/docs/src/System.IO.Temp.html#withTempDirectory) which is a bracket

**Comment by madeline-os** [comment]
The bracketing is broken and the ticket I made is supposed to be about fixing the bracketing. I'll make that more clear :sweat_smile:

**Pull request closed without merging**
