### PR TITLE
run: Set preferred host based on route

### LINKED ISSUE #719: ob run should not serve at 0.0.0.0
When developing an obelisk app locally, the server started by `ob run` is exposed to everyone on the network. 

Incidentally using `127.0.0.1` in common/route has no effect (`Run.hs:runWidget` sets only port, not host, from the route URI).

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #719 

I have:

  - [x] Based work on latest `develop` branch
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by 3noch** [comment]
@srid Does this solve your issue?

**Comment by srid** [comment]
@3noch It does, yes!

**Comment by 3noch** [comment]
Awesome. Thanks for the report.

**Comment by 3noch** [comment]
:thinking: It appears we no longer detect when two `ob run`s are using the same port. @tomsmalley can you confirm? I'm pretty sure that feature doesn't work on a mac anyway so this may only be reproducible on Linux.

**Comment by srid** [comment]
@3noch I can reproduce that on my NixOS machine. Seems strange to me that this particular change would cause that regression ...

**Comment by 3noch** [comment]
There's something about binding to a particular host that causes the binding to no longer *fail*.

**Pull request closed without merging**
