### PR TITLE
Recommend 'sandbox=relaxed'

### PR DESCRIPTION
**Pull request by alexfmpe**
`sandbox = true ` [is failing](https://github.com/obsidiansystems/obelisk/issues/52#issuecomment-394168617) for [mac os](https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L1809) nix builds.

### CODE REVIEW

**Comment by ryantrinkle** [comment]
@alexfmpe Has it been tested that this doesn't break #6?

**Comment by alexfmpe** [comment]
Not yet

**Comment by ryantrinkle** [comment]
Perhaps we could add something to the impure tests that test that and
this?  Also: i guess we need to set up some kind of CI for running the
impure tests on both macOS and Linux

**Comment by ali-abrar** [comment]
What does "relaxed" actually do? Sorry if I missed the explanation somewhere.

**Comment by alexfmpe** [comment]
From the manual:
> If this option is set to relaxed, then fixed-output derivations and derivations that have the __noChroot attribute set to true do not run in sandboxes.

We might have to change some things to allow running with `relaxed` though.
On macOS `sandbox=false` works while I'm getting

```nix-build -A ios.frontend -o result-ios --check
checking outputs of '/nix/store/xk4xhclhj6hf0z5nkfr5m32h3xwjb0hj-frontend-app.drv'...
++ mkdir -p /nix/store/6x98v2381hgdi8nwl8rf72k9hjmkbz3v-frontend-app/frontend.app
++ ln -s /nix/store/3g3557wcabdwafpkz4k3gcpfj86wr17n-Info.plist /nix/store/6x98v2381hgdi8nwl8rf72k9hjmkbz3v-frontend-app/frontend.app/Info.plist
ln: failed to create symbolic link '/nix/store/6x98v2381hgdi8nwl8rf72k9hjmkbz3v-frontend-app/frontend.app/Info.plist': File exists```

**Comment by alexfmpe** [comment]
#83 dealt with this

**Pull request closed without merging**
