### PR TITLE
WIP: Associate :/ With R

### PR DESCRIPTION
**Pull request by Ericson2314**
Makes importing easier

### CODE REVIEW

**Comment by alexfmpe** [comment]
Please yes

**Comment by 3noch** [comment]
Does this break modules that import `(:/)` as `pattern (:/)`? If so, we should probably export it both ways if possible.

**Comment by Ericson2314** [comment]
@3noch I believe it doesn't break that, but we should confirm.

**Comment by 3noch** [comment]
@Ericson2314 This was based on the wrong branch. It now has conflicts. :/

**Comment by Ericson2314** [comment]
I think it also needs a GHC change!

**Comment by 3noch** [comment]
wat?

**Comment by Ericson2314** [comment]
I think normal data constructors can be associated with a type synonym, but not patterns!

**Comment by madeline-os** [comment]
This is waiting on https://gitlab.haskell.org/ghc/ghc/-/issues/19507

**Comment by ryantrinkle** [comment]
If https://gitlab.haskell.org/ghc/ghc/-/issues/19507 is ever closed, please feel free to reopen this.

**Pull request closed without merging**
