### PR TITLE
Bump reflex-platform

### PR DESCRIPTION
**Pull request by kmicklas**
Fixes https://github.com/obsidiansystems/obelisk/issues/394 and https://github.com/obsidiansystems/obelisk/issues/369.

### CODE REVIEW

**Comment by ali-abrar** [comment]
@kmicklas would you mind including some more info in the commit message? We've got a lot of these "bump x" commits and I'd like us to start stating the reason.

**Comment by ali-abrar** [comment]
Something like "Bump nixpkgs to fix android 32 bit builds" perhaps?

**Comment by kmicklas** [comment]
@ali-abrar Done.

**Comment by ali-abrar** [comment]
Thanks. One last thing: I think a changelog entry would be good to have here, since we're basically (re-)adding support for 32-bit android. Might be interesting to know. You can add it under "Unreleased".

**Comment by rvl** [comment]
Excellent, thanks @kmicklas - I will try using the obelisk develop branch soon!

**Pull request merged**
