### PR TITLE
Put processed all.js files into an .assets directory

### PR DESCRIPTION
**Pull request by tomsmalley**
The consequence of this bug is all.js always 404s on full builds

I have:

  - [x] Based work on latest `develop` branch
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by 3noch** [comment]
This bug was introduced by https://github.com/obsidiansystems/obelisk/pull/778

**Review by 3noch — APPROVED** [review]
This fixes the bug.

**Comment by ryantrinkle** [comment]
@tomsmalley Why does this work?

**Comment by 3noch** [comment]
Possibly a better change would be to have `serverExe` rename them all while copying/symlinking as that would *also* preserve certain properties of the behavior before #778, but I'm not sure those properties matter.

**Comment by 3noch** [comment]
I changed it do just that because `compressedJs` is a publicly accessible function in `default.nix`. If anyone is relying on the naming scheme of that derivation (as `serverExe` was doing) then it would break their code. As unlikely as that is, it's easy enough to preserve behavior.

**Pull request merged**
