### PR TITLE
`staticFilesImpure` and not polluted assets library

### PR DESCRIPTION
**Pull request by Ericson2314**
The first commit exposes a `staticFilesImpure` to do things other than `toString staticFiles`. The second commit cleans things up so this incidental path doesn't pollute all the hashes (especially important with prod builds).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Not quite finished yet https://hydra.reflex-frp.org/eval/85748?compare=master#tabs-unfinished

**Comment by ryantrinkle** [comment]
@Ericson2314 @luigy Even if this fully works, I'm not sure it should be merged to master.  Let's make sure the interface we're exposing is clean enough that we're willing to support it for a while before we merge anything.

**Comment by Ericson2314** [comment]
So the second commit purely cleans things up and should definitely get in. The first commit exposes `staticFilesImpure`, which is the one new interface to think about.

**Comment by Ericson2314** [comment]
@ryantrinkle https://github.com/obsidiansystems/obelisk/pull/294/files contains just the second commit, which solves the deploy purity problem, without exposing any new interfaces. (`staticFilesImpure` is now let bound.)

**Comment by Ericson2314** [comment]
@ali-abrar This should still work just fine.

**Comment by Ericson2314** [comment]
Other plans supersede this.

**Pull request closed without merging**
