### PR TITLE
Make obelisk depend on reflex-dom-core instead of reflex-dom

### PR DESCRIPTION
**Pull request by matthewbauer**
All of the Obelisk libraries only need reflex-dom-core to work.
reflex-dom reexports reflex-dom-core, so this worked fine before, but
it had the side effect of pulling in jsaddle-webkit2gtk. For apps that
are just using jsaddle-warp, this pulls in a lot of GTK dependencies
that are never used. Switching everything to reflex-dom-core allows
individual apps avoid these extra dependencies.

### CODE REVIEW

**Comment by 3noch** [comment]
@matthewbauer Do you have any idea what the CI failures are about? If not I'll take a deeper look.

**Comment by 3noch** [comment]
Resolved merge conflicts.

**Comment by 3noch** [comment]
@matthewbauer Still having issues with CI. The errors are strange though, complaining about zlib?

**Comment by Ericson2314** [comment]
Android zlib errors I believe are fixed in newer reflex platform.

**Comment by matthewbauer** [comment]
I don't think it's been resolved - some weird error that only occurs when we don't pull in the extra dependencies from reflex-dom.

**Comment by 3noch** [comment]
#779 Should have solved the hard part of this.

**Pull request merged**
