### PR TITLE
Add COMPLETE pragma to (:/)

### PR DESCRIPTION
**Pull request by alexfmpe**

### CODE REVIEW

**Comment by ryantrinkle** [comment]
I originally didn't add that due to us being on a version of GHC that's too old; have you checked that we're on a new enough one now?

**Comment by kmicklas** [comment]
@ryantrinkle Reflex Platform `develop` now only uses GHC 8.4, and presumably we'll bump to that version at least before releasing Obelisk `master`.

**Comment by alexfmpe** [comment]
How about I add an `#ifdef` for now, and it'll get removed on the next pass cleaning up older ghc support?

**Comment by kmicklas** [comment]
Hoping to merge https://github.com/obsidiansystems/obelisk/pull/400/ soon.

**Comment by ali-abrar** [comment]
We're on ghc 8.4 now

**Comment by ali-abrar** [comment]
@alexfmpe please add a release notes entry

**Comment by alexfmpe** [comment]
@ali-abrar Rebased and done

**Comment by ali-abrar** [comment]
Thanks

**Pull request merged**
