### PR TITLE
Run all nix-builds with --sandbox

### LINKED ISSUE #28: Warn the user if sandboxing is not enabled
See https://github.com/obsidiansystems/obelisk/issues/6, in which a derivation failed to build correctly due to not being sandboxed.

We should warn the user anytime they are trying to nix-build something with obelisk and sandboxing is not enabled.

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #28

### CODE REVIEW

**Comment by 3noch** [comment]
selftest is failing for some reason on this. I'll fix it.

**Comment by 3noch** [comment]
I think we'll need to run `--sandbox` on only certain builds. I haven't looked deeply into it yet but some things fail to build with this flag.

**Comment by ryantrinkle** [comment]
Interesting; I'm surprised some things fail.  I did add `sandbox = true` to the installation instructions, but having this as a fallback also seems good.

**Comment by ali-abrar** [comment]
How does this relate to #55?

**Comment by alexfmpe** [comment]
I think the idea here is enforcing sandbox whenever possible.
#55 is more about the kind of sandbox that should be used (be it recommendation or enforcing).

**Comment by ryantrinkle** [comment]
@3noch Looks like this needs to be rebased/merged.

**Comment by ryantrinkle** [comment]
Also: should we be using 'relaxed' somehow?

**Comment by alexfmpe** [comment]
Hard to say at this point - it may very well be that #6 also happens with 'relaxed'. 
Also, neither setting seems to completely accept obelisk currently.
`true`: https://github.com/obsidiansystems/obelisk/pull/55#issuecomment-395419688 
`relaxed` : https://github.com/obsidiansystems/obelisk/issues/52#issuecomment-394168617

**Comment by 3noch** [comment]
Should we close this then? I don't think it's correct.

**Pull request closed without merging**
