### PR TITLE
Frontend: fix loading css file by ios app

### PR DESCRIPTION
**Pull request by bxrt**
A \<base href="/"\> element in the html string makes the ios app
look for (some of) its assets in `/static/` instead of where they
are:
`/private/var/containers/Bundle/Application/[BA9B...B8C]/frontend.app/static/`

There should probably be no base element in the html in a WKWebView
since the baseURL is set separately in a WKWebView.

Resolves: #790

I have:

  - [x] Based work on latest `develop` branch
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by bxrt** [comment]
Remote CI build failed. I am not sure what I can do about that. Please help.

**Comment by 3noch** [comment]
Thank you! CI failure was spurious. I'm retrying it.

**Comment by matthewbauer** [comment]
We have another baseTag at https://github.com/obsidiansystems/obelisk/blob/master/lib/frontend/src/Obelisk/Frontend.hs#L247. This is important because hydration requires the DOM to match.

I think the best solution here is to just disable it on wkwebview since we already have a base url set. Something like this:

```
baseTag :: forall route js t m. ObeliskWidget js t route m => RoutedT t route m ()
#ifdef APPLE_IOS
baseTag = blank
#else
baseTag = elAttr "base" ("href" =: "/") blank --TODO: Figure out the base URL from the routes
#endif
```

**Comment by 3noch** [comment]
We shouldn't have two *different* places that introduce the base tag though.

**Comment by o1lo01ol1o** [comment]
Any update on this?

**Comment by bxrt** [comment]
It turns out that changing
```baseTag = elAttr "base" ("href" =: "/") blank --TODO: Figure out the base URL from the routes```
to 
```baseTag = elAttr "base" ("href" =: "") blank --TODO: Figure out the base URL from the routes```
fixes the issue for ios and keeps the minimal obelisk application functional on the other platforms that I tried.
However, @matthewbauer mentions hydration. [I learned from Reddit](https://www.reddit.com/r/reflexfrp/comments/htonag/obeliskgeneratedstatic/fykcexf?utm_source=share&utm_medium=web2x&context=3) what hydration is, but I don't know how it is supposed to work and how much it depends on the value of the html base element.

I have also tried Matthew's proposal with the `#ifdef`, `#else` and `#endif`, but that didn't work. I assume because these are validated at compile time by the C-preprocessor and APPLE_IOS is not defined then.

**Comment by bxrt** [comment]
@3noch, @cgibbard, is there anything I am expected to do for this fix at this point?

**Comment by o1lo01ol1o** [comment]
ping

**Comment by ali-abrar** [comment]
@bxrt Thanks for this. Sorry for the wait.

**Pull request merged**
