### PR TITLE
Bump the recommended AMI version up to 18.09. 

### PR DESCRIPTION
**Pull request by benkolera**
This worked for me on a deploy just then (not that exact AMI, because I deployed to ap-southeast-2 :slightly_smiling_face: ).

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Nix 2.0 had a serious bug where `nix copy` ran out of memory https://github.com/NixOS/nix/issues/1681. I remember that it was mitigated in time for NixOS 18.09 but I'm not sure if it's still a concern. IIRC this is why we continued to recommend 17.09 even after 18.03 came out.

**Comment by ryantrinkle** [comment]
We should test this on an 18.09 nano instance; the larger instances never actually triggered the issue because they had enough RAM.

**Comment by benkolera** [comment]
I'm unsure of whether it's in 18.09. But @ali-abrar thought that it was dated info via IRC today.

If 18.09 is no good, 19.03 is right around the corner!

**Comment by benkolera** [comment]
Ahh yeah I tried it on a micro as per the docs. Can test it on a nano tomorrow if you'd like.

**Comment by ryantrinkle** [comment]
That would be great, thanks!  It was also broken on micro before, so it
sounds like the chance is good :)

**Comment by benkolera** [comment]
It worked on the nano just fine. Looks like the bug is gone! :slightly_smiling_face:

**Comment by ali-abrar** [comment]
Thanks!

**Comment by ryantrinkle** [comment]
@benkolera Fantastic; thanks for checking!

**Pull request merged**
