### PR TITLE
Error when invalid extensions are present in the Cabal file(s)

### LINKED ISSUE #483: Invalid `default-extensions` break `ob run` in very confusing way
Adding a non-existent extension (e.g. typo) to `default-extensions` makes it so that only module extensions are active. For instance, starting with the obelisk skeleton
```diff
    , mtl
    , text
  default-extensions:
+   GeneralisedNewtypeDeriving
    TypeFamilies
    PolyKinds
   exposed-modules:
```
causes `ob run` to error with 
```
common/src/Common/Route.hs:49:1: error:
    • Illegal family instance for ‘Data.Constraint.Extras.ConstraintsFor’
        (Use TypeFamilies to allow indexed type families)
    • In the type instance declaration for ‘Data.Constraint.Extras.ConstraintsFor’
      In the instance declaration for
        ‘Data.Constraint.Extras.ArgDict c_aaX5 FrontendRoute’
   |
49 | concat <$> mapM deriveRouteComponent
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
common/src/Common/Route.hs:49:1: error:
    • Illegal family instance for ‘Data.Constraint.Extras.ConstraintsFor’
        (Use TypeFamilies to allow indexed type families)
    • In the type instance declaration for ‘Data.Constraint.Extras.ConstraintsFor’
      In the instance declaration for
        ‘Data.Constraint.Extras.ArgDict c_aaX3 BackendRoute’
   |
49 | concat <$> mapM deriveRouteComponent
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

The error only becomes apparent when `nix-build -A ghc.common` fails with
 ```
Setup: The package common-0.1 requires the following language extensions which
are not supported by ghc-8.4.3: GeneralisedNewtypeDeriving
```
because the British spelling is [only available on 8.6](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#generalised-derived-instances-for-newtypes
).

### PR DESCRIPTION
**Pull request by plt-amy**
Fixes #483. Since the current behaviour for preprocessor failures is to close our eyes and hope for the best (that's the `Nothing` branches in the binding of `packageInfo'`), that's what I did, too.

I have:

  - [x] Based work on latest `develop` branch
  - [x] Followed the [contribution guide](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#submitting-changes)
  - [ ] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [x] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [x] [Updated the changelog](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#in-the-changelog)
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Review by madeline-os — APPROVED** [review]

**Comment by madeline-os** [comment]
Can we get a test for this?

**Comment by plt-amy** [comment]
@madeline-os I presume we should actually fail the build when the cabal file is un-parseable then?

**Review by madeline-os — APPROVED** [review]

**Comment by alexfmpe** [comment]
> Fixes https://github.com/obsidiansystems/obelisk/issues/483.

I still get the cycle though?

**Comment by alexfmpe** [comment]
Oh interesting, the cycle happens in `ob watch` but `ob run` errors as expected

**Pull request merged**
