### PR TITLE
Make obelisk-executable-config-inject more flexible

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by 3noch** [comment]
@luigy @ali-abrar Thoughts?

**Comment by 3noch** [comment]
@ryantrinkle?

**Comment by ryantrinkle** [comment]
@3noch can you elaborate on the purpose / use case for this?

**Comment by 3noch** [comment]
I wanted to enable some configs to be passed via command line arg in addition to the config file without actually overwriting any existing config file that is there. The way this library was implemented didn't make this possible. Factoring out the "injection encoding" as its own function allows more complex use cases to decide how to get the injection content differently (maybe from a db, env var, etc.).

**Comment by 3noch** [comment]
Granted `injectPure` isn't a great name. `encodeAsInjection` might be better.

**Comment by srid** [comment]
The typed config stuff presents an alternate way to achieve this.

**Pull request merged**
