### PR TITLE
Adding a combinator for handling with a non closed (non GADT) segment in a non leaf position of the route

### PR DESCRIPTION
**Pull request by benkolera**
This was to address a limitation that I hit when trying to encode this route structure mentioned in issue #361 . Namely:

/profile/:username
/profile/:username/favourites

This is tested [here](https://github.com/qfpl/reflex-realworld-example/blob/master/common/src/Common/Route.hs#L69) (this project is pointing at obelisk from my fork). If I change the ProfileRoute_Favourites segment to be PathEnd (unitEncoder mempty) it correctly fails the overlapping check because it clashes with the /profile/:username route, which is awesome and feels like it isn't a broken combinator from my naive view! 

I'm not sold on the name of the function. I was hoping that you'd have a good name for it or to just crush this PR with letting me know the intended way of encoding this kind of route! :slightly_smiling_face:

### CODE REVIEW

**Comment by benkolera** [comment]
When I was implementing the frontend using routes of this structure, it felt like you really wanted a complementary thing on the frontend that can pull the tuple apart and keep chaining RoutedT's below for sub routes (whatever b is in the tuple). 

See https://github.com/qfpl/reflex-realworld-example/commit/13709c5b47da78c47bf7ceb59b7cf7c602dbba2d for the use of the code from the second commit to this PR.

**Comment by benkolera** [comment]
Closing this. There was a pathSegmentEncoder introduced by #357 that does this more generally. 

See https://github.com/qfpl/reflex-realworld-example/blob/1bcf46da3853273134b4fb4192295d34bf84fa95/common/src/Common/Route.hs#L69-L71 for using that new work.

**Comment by cgibbard** [comment]
Is it strictly more general? I actually think that tuple encoder might be
handy anyway...

**Comment by cgibbard** [comment]
Ah, right, Dan's function is perhaps a more general thing despite the less
polymorphic type, just because you can use it toward the end of encoding.

**Comment by benkolera** [comment]
@cgibbard : General probably isn't the right word. It's more that my function mostly just does what Dan's does (it 'unconses' a Text segment off and gets the remaining PageName) and the only thing that my function does that Dan's doesn't actually overlaps with the Bifunctor (,) Encoder. With Dan's function, you can rewrite my function as:

```haskell
pathSegmentEncoder . bimap this rest
```

which makes it a syntactic shortcut at best, and probably a questionable one. :slightly_smiling_face: 

What is definitely handy would be a tutorial or docs that explained how to think of Encoders as categories and get them comfy with the power that the premade instances give them. It took me a little bit to figure out that bimap was what I needed and how to use it. I'll write these docs in my real-world example (or blog posts surrounding them), but I can submit them somewhere else if you think they'll be useful there.

**Pull request closed without merging**
