### PR TITLE
Fix breakage in `ob shell` and `ob hoogle`

### PR DESCRIPTION
**Pull request by madeline-os**
This was caused by #946 which accidentally replaced a use of
`runProcess_` with `runProc`. Similarly named, but different behavior.

Pondering: better way to test `ob shell` behavior.

Also pondering: better names!

I have:

  - [x] Based work on latest `develop` branch
  - [x] Followed the [contribution guide](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#submitting-changes)
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [ ] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [x] [Updated the changelog](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#in-the-changelog)
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

### CODE REVIEW

**Comment by madeline-os** [comment]
@alexfmpe email me ur contact info so we can stay in touch better!

**Comment by alexfmpe** [comment]
LGTM. Old behavior is back

**Review by plt-amy — COMMENTED** [review]
LGTM

**Review by alexfmpe — APPROVED** [review]

**Review by plt-amy — APPROVED** [review]
LGTM

**Comment by plt-amy** [comment]
Damned github won't let me change my comment to an approval and I noticed too late. Fantastic. Great

**Review by ryantrinkle — APPROVED** [review]

**Pull request merged**
