### PR TITLE
Obelisk.CliApp.Process: reconstruct commands on display

### PR DESCRIPTION
**Pull request by vaibhavsagar**
This makes them easier to copy and debug when things go wrong.

### CODE REVIEW

**Comment by 3noch** [comment]
I've wanted this too! Thanks! When a raw command gets reconstructed, it might have very different semantics to what was actually run. Better would be to quote each argument and apply escaping.

**Comment by 3noch** [comment]
This might help: https://github.com/obsidiansystems/obelisk/blob/495f20ccf033a7700fb8afaca40229dedd9d161b/lib/command/src/Obelisk/Command/Utils.hs#L65

**Comment by ryantrinkle** [comment]
Let's escape the arguments when they need it. Also, why not keep CmdSpec in
the error datatype?

**Comment by vaibhavsagar** [comment]
Thanks @3noch, I've duplicated that function because `obelisk-cliapp` is a dependency of `obelisk-command` so I couldn't import it. @ryantrinkle I did that primarily to avoid writing a `Show` instance but that's not a good reason so I've changed it back.

**Comment by ryantrinkle** [comment]
The human-readable output shouldn't be produced by `show`. We should have
another function (or class)

**Comment by vaibhavsagar** [comment]
Okay, I've instead defined `displayException` to provide the expected behaviour (that an error message contains a command that the user can copy and reuse as-is).

**Comment by luigy** [comment]
Thanks! would it be more helpful if it also printed the absolute path of the exe?

**Comment by ryantrinkle** [comment]
@luigy Hmm, is the PATH usually different from the ambient PATH?

**Comment by ryantrinkle** [comment]
(@luigy regardless, I think we don't have to hold up this merge for that)

**Comment by luigy** [comment]
Agreed, this is already an improvement over what we currently have

**Comment by luigy** [comment]
thanks @vaibhavsagar

**Comment by vaibhavsagar** [comment]
My pleasure :smile:!

**Pull request merged**
