### PR TITLE
Flexible backend port

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by luigy** [comment]
This is better than before, but now I wonder where is the `--port` parsing actually happening? `obelisk-backend` is aiming to be backend agnostic, but not quite there yet

**Comment by luigy** [comment]
this may just be a leftover that is now fully handled by `config/common/route`

**Comment by 3noch** [comment]
@luigy The port parsing is being done by snap. The previous behavior was to use the default port and implicitly imply that it was 8000. This forces you to pick the same port for the server and the `proxyPass`. But yes ideally we'd have a better, backend-agnostic way.

**Comment by 3noch** [comment]
Note that *not* specifying a port (i.e. the previous way) is also not backend agnostic. :)

**Comment by luigy** [comment]
Oh yeah I just meant to note it as an improvement  :)

**Comment by 3noch** [comment]
Righteo!

**Pull request merged**
